version: '3'

services:
  app:
    build:
      context: ./app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/ecommerce
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=rootpassword
    depends_on:
      - db

  db:
    build:
      context: ./db
    ports:
      - "3306:3306"

  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - app
